# Generated by Django 3.2.10 on 2022-02-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_super', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=250, null=True)),
            ],
        ),
    ]
