# Generated by Django 3.2.10 on 2022-04-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('IR', 'Iran'), ('JP', 'Japan'), ('TU', 'Turkey')], max_length=20, null=True),
        ),
    ]
